import sys,glob
import os
   
expected_dir = "/home/App/stations/migrations"                                   
for file_name_relative in glob.glob(expected_dir+"/000*.py",recursive=True): 
    file_name = os.path.basename(file_name_relative)
number_of_file = int(file_name[3]) + 1
first_part_name = "000" + str(number_of_file)
second_part_name = "_create_custom_index.py"
file_name_end = first_part_name + second_part_name
f = open(expected_dir + "/" + file_name_end,"w+")

sql_file_path = "migration_sql.sql"
sql_file = open(sql_file_path)
sql_query = sql_file.read()
sql_file.close()

f.write(
'''# Generated by Django 3.0.3 on 2020-10-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations',\'{}\'),
    ]

    operations = [
        migrations.RunSQL("""{}""")
    ]
'''.format(file_name[:-3], sql_query))